/**
 * dom-refs.js - Centralized DOM references shared across modules
 * @returns {Object} DOM references map
 */
export function getDomRefs() {
	return {
		authView: document.querySelector("#authView"),
		authForm: document.querySelector("#authForm"),
		authUsernameInput: document.querySelector("#authUsername"),
		authHint: document.querySelector("#authHint"),
		appShell: document.querySelector("#appShell"),
		logoutBtn: document.querySelector("#logoutBtn"),
		alertBox: document.querySelector("#alertBox"),
		formView: document.querySelector("#formView"),
		listView: document.querySelector("#listView"),
		showFormBtn: document.querySelector("#showFormBtn"),
		showListBtn: document.querySelector("#showListBtn"),
		formTitle: document.querySelector("#formTitle"),
		submitBtn: document.querySelector("#submitBtn"),
		cancelEditBtn: document.querySelector("#cancelEditBtn"),
		contactForm: document.querySelector("#contactForm"),
		avatarPreview: document.querySelector("#avatarPreview"),
		avatarFileInput: document.querySelector("#avatarFile"),
		avatarUrlInput: document.querySelector("#avatarUrl"),
		countryCodeSelect: document.querySelector("#countryCode"),
		countryIsoInput: document.querySelector("#countryIso"),
		countryDropdownBtn: document.querySelector("#countryDropdownBtn"),
		countryDropdownList: document.querySelector("#countryDropdownList"),
		countryDropdownOptions: document.querySelector("#countryDropdownOptions"),
		countryNoResults: document.querySelector("#countryNoResults"),
		themeTglBtn: document.querySelector("#themeTglBtn"),
		themeIcon: document.querySelector("#themeIcon"),
		searchBar: document.querySelector("#searchBar"),
		globalSearchInput: document.querySelector("#globalSearchInput"),
		contactsGrid: document.querySelector("#contactsGrid"),
		noContactsMsg: document.querySelector("#noContactsMsg"),
		paginationNav: document.querySelector("#paginationNav"),
		paginationList: document.querySelector("#paginationList"),
		accountSettingsBtn: document.querySelector("#accountSettingsBtn"),
		accountModal: document.querySelector("#accountModal"),
		changePasswordBtn: document.querySelector("#changePasswordBtn"),
		deleteAccountBtn: document.querySelector("#deleteAccountBtn"),
		favoriteFilterBtn: document.querySelector("#favoriteFilterBtn"),
		exportBookBtn: document.querySelector("#exportBookBtn"),
		importBookBtn: document.querySelector("#importBookBtn"),
		importFileInput: document.querySelector("#importFileInput"),
		tagFilterContainer: document.querySelector("#tagFilterContainer"),
		contactModal: document.querySelector("#contactModal"),
		contactModalAvatar: document.querySelector("#contactModalAvatar"),
		contactModalName: document.querySelector("#contactModalName"),
		contactModalEmail: document.querySelector("#contactModalEmail"),
		contactModalPhone: document.querySelector("#contactModalPhone"),
		contactModalAge: document.querySelector("#contactModalAge"),
		contactModalTags: document.querySelector("#contactModalTags"),
		contactModalCreatedBy: document.querySelector("#contactModalCreatedBy"),
		contactModalEditBtn: document.querySelector("#contactModalEditBtn"),
		contactModalDeleteBtn: document.querySelector("#contactModalDeleteBtn"),
		undoToastEl: document.querySelector("#undoToast"),
		undoToastBtn: document.querySelector("#undoToastBtn")
	};
}

